### ISSUE TITLE
Docker Image and fresh build of docker image run into an error

### ISSUE THREAD

**Issue by AceXare** [danifr/get-keycloak-docs#7]
By running the docker image provided by the dockerhub, or by building an own image of the project, running the container with the provided documentation into the following exception:

```bash
➜  get-keycloak-docs git:(master) ✗ sudo docker run -i -t --rm -v /tmp/keycloak_docs/:/output dafero/get-keycloak-docs:v2.1.2
Traceback (most recent call last):
  File "get_keycloak_docs.py", line 20, in <module>
    from readability.readability import Document
  File "/root/.local/lib/python3.8/site-packages/readability/__init__.py", line 3, in <module>
    from .readability import Document
  File "/root/.local/lib/python3.8/site-packages/readability/readability.py", line 13, in <module>
    from .cleaners import clean_attributes
  File "/root/.local/lib/python3.8/site-packages/readability/cleaners.py", line 3, in <module>
    from lxml.html.clean import Cleaner
  File "/root/.local/lib/python3.8/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

I am not very experienced with the python libraries, therefore not really sure what the issue may be here.

**Comment by AceXare** [comment]
ah it seems the used package got split into multiple packages, therefore extending requirements.txt by "lxml_html_clean" seems to be enough
